-- ═════════════════════════════════════════════════════════════════
-- CHAT — SERVER-SIDE ENCRYPTION AT REST (replaces client-side E2E)
-- Run this once in the Supabase SQL editor, top to bottom.
--
-- WHY THIS REPLACES THE OLD SYSTEM
-- The previous design (js/chat-crypto.js, chat_e2e_encryption.sql,
-- chat_key_backup.sql) encrypted messages client-side with a key that
-- lived only in the browser that generated it. That meant every new
-- device started with no way to read old messages unless a passphrase
-- backup had been restored FIRST — and the old code generated/
-- published a throwaway key before giving the person that chance,
-- permanently orphaning messages in the process. That's the
-- "can't decrypt this message on this device" bug.
--
-- This migration removes that whole failure mode. Messages are now
-- encrypted at rest by Postgres itself (pgcrypto, AES via
-- pgp_sym_encrypt) using a single secret key stored in Supabase Vault
-- — never sent to or generated by the browser, never tied to any one
-- device. Every authenticated device that's allowed to read a message
-- (sender/recipient, or a conversation member for groups/channels)
-- can decrypt it immediately, on any browser, with no passphrase.
--
-- WHAT THIS DOES NOT PROTECT AGAINST
-- Being honest about the trade-off: this is encryption AT REST, not
-- end-to-end. Supabase infrastructure (and anyone who obtained the
-- Vault secret or full DB access) could technically decrypt messages
-- server-side. It protects against a stolen/leaked DATABASE BACKUP or
-- disk being readable as plaintext, and it's what the RPC functions
-- below use to keep decryption behind the same access checks the app
-- already relies on for everything else (RLS, auth.uid()). It's a
-- deliberate trade for a chat feature that reliably works on any
-- device with no key-loss failure mode, chosen instead of true E2E
-- after the E2E design proved to lose messages in practice.
--
-- WHAT THIS FILE DOES
--   1. Stores a fresh random secret key in Supabase Vault.
--   2. Adds messages.body_encrypted to distinguish new
--      server-encrypted rows from legacy rows (old E2E ciphertext, or
--      genuinely old plaintext) — legacy rows are left exactly as
--      they are; this migration does not try to re-encrypt or recover
--      them (old E2E rows still need the OLD passphrase-restore flow
--      if you still want a shot at reading them — see note at bottom).
--   3. A BEFORE INSERT trigger that transparently encrypts body for
--      every new message — 1:1 DMs, group messages, and channel
--      posts alike (groups/channels were plaintext before this).
--   4. Three SECURITY DEFINER RPC functions that decrypt on read,
--      re-implementing the exact same access rules as the table's
--      existing RLS policies (only a message's sender/recipient, or a
--      conversation member, ever gets decrypted text back).
--   5. Drops the old E2E-only columns' further use going forward
--      (pubkey/key_backup/iv are left in place, unused, rather than
--      dropped outright — see note at bottom on why).
-- ═════════════════════════════════════════════════════════════════

create extension if not exists pgcrypto;

-- ── 1. SECRET KEY (Supabase Vault) ──
-- Vault (pgsodium-backed) is Supabase's supported place for secrets
-- that application code needs but that should never be readable via
-- the anon/authenticated Postgres roles — exactly what we need here.
-- Only run vault.create_secret() the FIRST time; re-running this
-- migration must not rotate the key (that would make every existing
-- server-encrypted message undecryptable), so it's guarded.
do $$
begin
  if not exists (select 1 from vault.secrets where name = 'chat_body_key') then
    perform vault.create_secret(
      encode(gen_random_bytes(32), 'hex'),
      'chat_body_key',
      'Symmetric key used to encrypt chat message bodies at rest (pgp_sym_encrypt). Do not rotate without a migration plan for existing rows.'
    );
  end if;
end $$;

-- Internal-only accessor — never granted to anon/authenticated, only
-- callable from the SECURITY DEFINER functions below (which run with
-- this function owner's privileges).
create or replace function public._chat_secret()
returns text
language sql
stable
security definer
set search_path = public, vault
as $$
  select decrypted_secret from vault.decrypted_secrets where name = 'chat_body_key' limit 1;
$$;

revoke all on function public._chat_secret() from public, anon, authenticated;

-- Safe decrypt wrapper — pgp_sym_decrypt() RAISES (Postgres's literal
-- error text is "Wrong key or corrupt data") on any ciphertext it
-- can't decrypt. Called bare inside the jsonb_agg() queries below,
-- that exception would abort the WHOLE function call over a single
-- bad row, blanking an entire chat list/thread. Routing through here
-- instead catches that per-row and returns null, which js/chat.js
-- already renders as the undecryptable-message placeholder bubble.
create or replace function public._chat_decrypt(enc_body text, is_encrypted boolean)
returns text
language plpgsql
stable
security definer
set search_path = public, vault
as $$
begin
  if not is_encrypted then
    return enc_body;
  end if;
  if enc_body is null then
    return null;
  end if;
  return convert_from(pgp_sym_decrypt(decode(enc_body, 'base64'), public._chat_secret()), 'UTF8');
exception
  when others then
    return null;
end;
$$;

revoke all on function public._chat_decrypt(text, boolean) from public, anon, authenticated;

-- ── 2. body_encrypted FLAG ──
-- true  = body holds base64 pgp_sym_encrypt ciphertext from this
--         migration's trigger (decrypt with public._chat_secret()).
-- false = legacy row — either genuinely-plaintext (very old messages,
--         or group/channel messages sent before this migration) or
--         old-format client-side E2E ciphertext (base64 AES-GCM, see
--         messages.iv). The RPC functions below pass these through
--         as-is; the client still knows how to show the old
--         "can't decrypt on this device" state for iv-tagged rows if
--         you keep any of that UI, or you can treat them as
--         unrecoverable — see the note at the bottom of this file.
alter table public.messages add column if not exists body_encrypted boolean not null default false;

comment on column public.messages.body_encrypted is
  'true = body is server-side ciphertext (pgp_sym_encrypt via public._chat_secret()), decrypt through get_dm_thread/get_dm_list/get_group_thread/get_message. false = legacy row (old plaintext or old client-side E2E ciphertext) — used as-is.';

-- ── 3. ENCRYPT ON INSERT ──
-- Runs for every message row regardless of context (1:1 DM or
-- group/channel — messages.conversation_id distinguishes them, this
-- trigger doesn't care). Empty/NULL body (caption-less attachment) is
-- left alone rather than encrypting an empty string.
create or replace function public.messages_encrypt_body()
returns trigger
language plpgsql
security definer
set search_path = public, vault
as $$
begin
  if new.body is not null and new.body <> '' then
    new.body := encode(pgp_sym_encrypt(new.body, public._chat_secret()), 'base64');
    new.body_encrypted := true;
  else
    new.body_encrypted := false;
  end if;
  -- New rows are never old-format E2E ciphertext — make sure iv is
  -- never set going forward so body_encrypted is the only flag any
  -- reader needs to check.
  new.iv := null;
  return new;
end;
$$;

drop trigger if exists messages_encrypt_body_trg on public.messages;
create trigger messages_encrypt_body_trg
  before insert on public.messages
  for each row execute function public.messages_encrypt_body();

-- ── 4. DECRYPT-ON-READ RPCs ──
-- Each one is SECURITY DEFINER (so it can call public._chat_secret()
-- and read ciphertext regardless of the table's own RLS) but manually
-- re-checks auth.uid() against the exact same rule the table's RLS
-- policies already enforce, so nobody can use these to read a
-- conversation they're not part of. Returns jsonb: same shape as the
-- underlying row (via to_jsonb) with body swapped for plaintext, so
-- existing client code that reads m.id / m.media_url / etc. keeps
-- working unchanged.

-- 1:1 DM thread with one other user, newest-last (matches the old
-- direct .select('*') in loadThread()).
create or replace function public.get_dm_thread(other_user_id uuid, msg_limit int default 500)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, vault
as $$
declare
  me uuid := auth.uid();
  result jsonb;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select coalesce(jsonb_agg(row order by created_at asc), '[]'::jsonb) into result
  from (
    select
      m.created_at,
      to_jsonb(m) || jsonb_build_object(
        'body', public._chat_decrypt(m.body, m.body_encrypted)
      ) as row
    from public.messages m
    where m.conversation_id is null
      and ((m.sender_id = me and m.recipient_id = other_user_id)
        or (m.sender_id = other_user_id and m.recipient_id = me))
    order by m.created_at asc
    limit msg_limit
  ) t;
  return result;
end;
$$;

revoke all on function public.get_dm_thread(uuid, int) from public, anon;
grant execute on function public.get_dm_thread(uuid, int) to authenticated;

-- 1:1 DM conversation list — every message I've sent or received,
-- newest-first, with sender/recipient profile info embedded (matches
-- the old embedded-resource select in loadConversationList()).
create or replace function public.get_dm_list(row_limit int default 300)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, vault
as $$
declare
  me uuid := auth.uid();
  result jsonb;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select coalesce(jsonb_agg(row order by created_at desc), '[]'::jsonb) into result
  from (
    select
      m.created_at,
      to_jsonb(m) || jsonb_build_object(
        'body', public._chat_decrypt(m.body, m.body_encrypted),
        'sender', jsonb_build_object('id', sp.id, 'username', sp.username, 'display_name', sp.display_name, 'avatar_url', sp.avatar_url, 'verified', sp.verified, 'verification_type', sp.verification_type),
        'recipient', jsonb_build_object('id', rp.id, 'username', rp.username, 'display_name', rp.display_name, 'avatar_url', rp.avatar_url, 'verified', rp.verified, 'verification_type', rp.verification_type)
      ) as row
    from public.messages m
    join public.profiles sp on sp.id = m.sender_id
    left join public.profiles rp on rp.id = m.recipient_id
    where m.conversation_id is null and (m.sender_id = me or m.recipient_id = me)
    order by m.created_at desc
    limit row_limit
  ) t;
  return result;
end;
$$;

revoke all on function public.get_dm_list(int) from public, anon;
grant execute on function public.get_dm_list(int) to authenticated;

-- Group/channel thread — same idea, gated on conversation membership
-- (mirrors messages_select_conversation's RLS predicate exactly).
create or replace function public.get_group_thread(conv_id uuid, msg_limit int default 500)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, vault
as $$
declare
  me uuid := auth.uid();
  result jsonb;
begin
  if me is null then raise exception 'not authenticated'; end if;
  if not exists (select 1 from public.conversation_members cm where cm.conversation_id = conv_id and cm.user_id = me) then
    raise exception 'not a member of this conversation';
  end if;
  select coalesce(jsonb_agg(row order by created_at asc), '[]'::jsonb) into result
  from (
    select
      m.created_at,
      to_jsonb(m) || jsonb_build_object(
        'body', public._chat_decrypt(m.body, m.body_encrypted)
      ) as row
    from public.messages m
    where m.conversation_id = conv_id
    order by m.created_at asc
    limit msg_limit
  ) t;
  return result;
end;
$$;

revoke all on function public.get_group_thread(uuid, int) from public, anon;
grant execute on function public.get_group_thread(uuid, int) to authenticated;

-- Last message per group/channel, for the conversation-list snippet
-- previews (mirrors the second query in loadMyGroupRows()).
create or replace function public.get_group_last_messages(conv_ids uuid[])
returns jsonb
language plpgsql
stable
security definer
set search_path = public, vault
as $$
declare
  me uuid := auth.uid();
  result jsonb;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select coalesce(jsonb_agg(row), '[]'::jsonb) into result
  from (
    select distinct on (m.conversation_id)
      to_jsonb(m) || jsonb_build_object(
        'body', public._chat_decrypt(m.body, m.body_encrypted),
        'sender', jsonb_build_object('username', sp.username, 'display_name', sp.display_name)
      ) as row
    from public.messages m
    join public.profiles sp on sp.id = m.sender_id
    where m.conversation_id = any(conv_ids)
      and exists (select 1 from public.conversation_members cm where cm.conversation_id = m.conversation_id and cm.user_id = me)
    order by m.conversation_id, m.created_at desc
  ) t;
  return result;
end;
$$;

revoke all on function public.get_group_last_messages(uuid[]) from public, anon;
grant execute on function public.get_group_last_messages(uuid[]) to authenticated;

-- Single message by id — used to resolve a realtime INSERT
-- notification (which streams the raw encrypted row) to its plaintext
-- before rendering it. Works for both DM and group/channel messages.
create or replace function public.get_message(msg_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, vault
as $$
declare
  me uuid := auth.uid();
  result jsonb;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select to_jsonb(m) || jsonb_build_object(
    'body', public._chat_decrypt(m.body, m.body_encrypted)
  ) into result
  from public.messages m
  where m.id = msg_id
    and (
      (m.conversation_id is null and (m.sender_id = me or m.recipient_id = me))
      or (m.conversation_id is not null and exists (
            select 1 from public.conversation_members cm
            where cm.conversation_id = m.conversation_id and cm.user_id = me))
    );
  if result is null then raise exception 'not found or not authorized'; end if;
  return result;
end;
$$;

revoke all on function public.get_message(uuid) from public, anon;
grant execute on function public.get_message(uuid) to authenticated;

notify pgrst, 'reload schema';

-- ═════════════════════════════════════════════════════════════════
-- NOTE ON OLD E2E DATA
-- profiles.pubkey, profiles.key_backup, and messages.iv are left in
-- place (not dropped) so any thread that was successfully encrypted
-- under the OLD client-side system is not made instantly
-- unreadable by this migration — those rows still have
-- body_encrypted = false and iv set, and the app's old
-- js/chat-crypto.js restore flow is the only way to read them if you
-- kept that code around for exactly that purpose. Anything encrypted
-- under the old system to a throwaway key that was never backed up
-- was already unrecoverable before this migration and remains so —
-- no migration can decrypt data whose key no longer exists anywhere.
-- Once you're confident nothing important is stuck in old encrypted
-- threads, these three columns can be dropped in a follow-up
-- migration.
-- ═════════════════════════════════════════════════════════════════
