-- ═════════════════════════════════════════════════════════════════
-- CHAT ENCRYPTION — canonical version. Run this once, top to bottom,
-- in the Supabase SQL editor. Safe to re-run any time (every object
-- is created with create-or-replace / if-not-exists).
--
-- This is the ONLY encryption file the project needs going forward.
-- It supersedes and replaces:
--   chat_e2e_encryption.sql       (old client-side E2E — retired)
--   chat_key_backup.sql           (old E2E passphrase backup — retired)
--   chat_server_side_encryption.sql (superseded, folded in here)
--   chat_decrypt_fix.sql          (superseded, folded in here)
-- Delete those four files from the repo; nothing depends on them.
--
-- DESIGN
-- Messages are encrypted at rest (AES via pgcrypto's pgp_sym_encrypt)
-- with one secret key held in Supabase Vault — never sent to or
-- generated by the browser. Any authenticated device the sender/
-- recipient/conversation-member checks allow can decrypt instantly,
-- with no passphrase and no per-device key state. This is encryption
-- AT REST (protects a leaked DB backup/disk), not end-to-end — Supabase
-- infra or DB access could technically decrypt. That trade-off is
-- deliberate: the previous true-E2E design generated a throwaway
-- per-device key before the person had a chance to back it up,
-- silently orphaning messages. This design has no such failure mode.
--
-- ROBUSTNESS
-- Every decrypt goes through public._chat_decrypt(), which catches
-- any failure (corrupt ciphertext, truncated data, anything) per-row
-- and returns NULL instead of raising. One bad row can never take
-- down an entire chat list/thread — the worst case is that one
-- message renders as "can't be decrypted" in the UI (see
-- js/chat.js -> msgBubbleHtml) while everything else works normally.
--
-- SCHEMA NOTE
-- Supabase installs pgcrypto into a schema called `extensions`, not
-- `public`. Every function below sets search_path to explicitly
-- include it (public, extensions, vault) — omitting it is why
-- pgp_sym_encrypt/pgp_sym_decrypt would fail with "function ...
-- does not exist" even though the extension is enabled.
-- ═════════════════════════════════════════════════════════════════

create extension if not exists pgcrypto;

-- ── 1. SECRET KEY (Supabase Vault) ──
-- Guarded so re-running this file never rotates the key (which would
-- make every existing encrypted message permanently unreadable).
do $$
begin
  if not exists (select 1 from vault.secrets where name = 'chat_body_key') then
    perform vault.create_secret(
      encode(gen_random_bytes(32), 'hex'),
      'chat_body_key',
      'Symmetric key used to encrypt chat message bodies at rest (pgp_sym_encrypt). Do not rotate without a migration plan for existing rows.'
    );
  end if;
end $$;

create or replace function public._chat_secret()
returns text
language sql
stable
security definer
set search_path = public, extensions, vault
as $$
  select decrypted_secret from vault.decrypted_secrets where name = 'chat_body_key' limit 1;
$$;

revoke all on function public._chat_secret() from public, anon, authenticated;

-- ── 2. SAFE DECRYPT ──
-- The single place pgp_sym_decrypt() is ever called from. Catches
-- every failure mode and returns NULL rather than raising, so a bad
-- row degrades gracefully instead of aborting the whole query.
create or replace function public._chat_decrypt(enc_body text, is_encrypted boolean)
returns text
language plpgsql
stable
security definer
set search_path = public, extensions, vault
as $$
begin
  if not is_encrypted then
    return enc_body;
  end if;
  if enc_body is null or enc_body = '' then
    return null;
  end if;
  return convert_from(pgp_sym_decrypt(decode(enc_body, 'base64'), public._chat_secret()), 'UTF8');
exception
  when others then
    return null;
end;
$$;

revoke all on function public._chat_decrypt(text, boolean) from public, anon, authenticated;

-- ── 3. body_encrypted FLAG ──
alter table public.messages add column if not exists body_encrypted boolean not null default false;

comment on column public.messages.body_encrypted is
  'true = body is ciphertext from public._chat_secret() (pgp_sym_encrypt), decrypt via public._chat_decrypt(). false = legacy/plaintext row.';

-- ── 4. ENCRYPT ON INSERT ──
-- Runs for every new message (1:1 DM, group, channel alike). Empty/
-- NULL body (caption-less attachment) is left alone.
create or replace function public.messages_encrypt_body()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, vault
as $$
begin
  if new.body is not null and new.body <> '' then
    new.body := encode(pgp_sym_encrypt(new.body, public._chat_secret()), 'base64');
    new.body_encrypted := true;
  else
    new.body_encrypted := false;
  end if;
  -- New rows are never old-format E2E ciphertext.
  new.iv := null;
  return new;
end;
$$;

drop trigger if exists messages_encrypt_body_trg on public.messages;
create trigger messages_encrypt_body_trg
  before insert on public.messages
  for each row execute function public.messages_encrypt_body();

-- ── 5. DECRYPT-ON-READ RPCs ──
-- Each is SECURITY DEFINER (to call _chat_secret()/read ciphertext
-- past RLS) but manually re-checks auth.uid() against the exact same
-- rule the table's own RLS policies enforce, so nobody can use these
-- to read a conversation they're not part of.

create or replace function public.get_dm_thread(other_user_id uuid, msg_limit int default 500)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, extensions, vault
as $$
declare
  me uuid := auth.uid();
  result jsonb;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select coalesce(jsonb_agg(row order by created_at asc), '[]'::jsonb) into result
  from (
    select
      m.created_at,
      to_jsonb(m) || jsonb_build_object('body', public._chat_decrypt(m.body, m.body_encrypted)) as row
    from public.messages m
    where m.conversation_id is null
      and ((m.sender_id = me and m.recipient_id = other_user_id)
        or (m.sender_id = other_user_id and m.recipient_id = me))
    order by m.created_at asc
    limit msg_limit
  ) t;
  return result;
end;
$$;

revoke all on function public.get_dm_thread(uuid, int) from public, anon;
grant execute on function public.get_dm_thread(uuid, int) to authenticated;

create or replace function public.get_dm_list(row_limit int default 300)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, extensions, vault
as $$
declare
  me uuid := auth.uid();
  result jsonb;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select coalesce(jsonb_agg(row order by created_at desc), '[]'::jsonb) into result
  from (
    select
      m.created_at,
      to_jsonb(m) || jsonb_build_object(
        'body', public._chat_decrypt(m.body, m.body_encrypted),
        'sender', jsonb_build_object('id', sp.id, 'username', sp.username, 'display_name', sp.display_name, 'avatar_url', sp.avatar_url, 'verified', sp.verified, 'verification_type', sp.verification_type),
        'recipient', jsonb_build_object('id', rp.id, 'username', rp.username, 'display_name', rp.display_name, 'avatar_url', rp.avatar_url, 'verified', rp.verified, 'verification_type', rp.verification_type)
      ) as row
    from public.messages m
    join public.profiles sp on sp.id = m.sender_id
    left join public.profiles rp on rp.id = m.recipient_id
    where m.conversation_id is null and (m.sender_id = me or m.recipient_id = me)
    order by m.created_at desc
    limit row_limit
  ) t;
  return result;
end;
$$;

revoke all on function public.get_dm_list(int) from public, anon;
grant execute on function public.get_dm_list(int) to authenticated;

create or replace function public.get_group_thread(conv_id uuid, msg_limit int default 500)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, extensions, vault
as $$
declare
  me uuid := auth.uid();
  result jsonb;
begin
  if me is null then raise exception 'not authenticated'; end if;
  if not exists (select 1 from public.conversation_members cm where cm.conversation_id = conv_id and cm.user_id = me) then
    raise exception 'not a member of this conversation';
  end if;
  select coalesce(jsonb_agg(row order by created_at asc), '[]'::jsonb) into result
  from (
    select
      m.created_at,
      to_jsonb(m) || jsonb_build_object('body', public._chat_decrypt(m.body, m.body_encrypted)) as row
    from public.messages m
    where m.conversation_id = conv_id
    order by m.created_at asc
    limit msg_limit
  ) t;
  return result;
end;
$$;

revoke all on function public.get_group_thread(uuid, int) from public, anon;
grant execute on function public.get_group_thread(uuid, int) to authenticated;

create or replace function public.get_group_last_messages(conv_ids uuid[])
returns jsonb
language plpgsql
stable
security definer
set search_path = public, extensions, vault
as $$
declare
  me uuid := auth.uid();
  result jsonb;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select coalesce(jsonb_agg(row), '[]'::jsonb) into result
  from (
    select distinct on (m.conversation_id)
      to_jsonb(m) || jsonb_build_object(
        'body', public._chat_decrypt(m.body, m.body_encrypted),
        'sender', jsonb_build_object('username', sp.username, 'display_name', sp.display_name)
      ) as row
    from public.messages m
    join public.profiles sp on sp.id = m.sender_id
    where m.conversation_id = any(conv_ids)
      and exists (select 1 from public.conversation_members cm where cm.conversation_id = m.conversation_id and cm.user_id = me)
    order by m.conversation_id, m.created_at desc
  ) t;
  return result;
end;
$$;

revoke all on function public.get_group_last_messages(uuid[]) from public, anon;
grant execute on function public.get_group_last_messages(uuid[]) to authenticated;

create or replace function public.get_message(msg_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, extensions, vault
as $$
declare
  me uuid := auth.uid();
  result jsonb;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select to_jsonb(m) || jsonb_build_object('body', public._chat_decrypt(m.body, m.body_encrypted)) into result
  from public.messages m
  where m.id = msg_id
    and (
      (m.conversation_id is null and (m.sender_id = me or m.recipient_id = me))
      or (m.conversation_id is not null and exists (
            select 1 from public.conversation_members cm
            where cm.conversation_id = m.conversation_id and cm.user_id = me))
    );
  if result is null then raise exception 'not found or not authorized'; end if;
  return result;
end;
$$;

revoke all on function public.get_message(uuid) from public, anon;
grant execute on function public.get_message(uuid) to authenticated;

notify pgrst, 'reload schema';

-- ── 6. SELF-TEST ──
-- Confirms the whole pipeline (secret readable, encrypt, decrypt) is
-- healthy right now, independent of any table data.
do $$
declare
  test_plain text := 'chat_pipeline_selftest_' || gen_random_uuid();
  test_result text;
begin
  test_result := public._chat_decrypt(encode(pgp_sym_encrypt(test_plain, public._chat_secret()), 'base64'), true);
  if test_result = test_plain then
    raise notice '✅ Chat encryption is set up and working.';
  else
    raise notice '❌ Self-test failed — decrypted value did not match. Check the chat_body_key Vault secret.';
  end if;
end $$;

-- ═════════════════════════════════════════════════════════════════
-- NOTE ON OLD DATA
-- messages.iv is left in place (not dropped): any row where
-- body_encrypted = false and iv is not null is a message from the
-- retired client-side E2E system, whose key never existed server-
-- side and is not recoverable by this or any migration. The app
-- already renders those (and any row that fails to decrypt for any
-- other reason) as "This message can't be decrypted." — see
-- msgBubbleHtml() in js/chat.js. Once you're confident nothing
-- important is stuck in old threads, `iv` can be dropped in a
-- follow-up migration; it's inert otherwise.
-- ═════════════════════════════════════════════════════════════════
